name               = "tobnoonechatgptnextweb"
main               = "./public/serviceWorker.js"  # 你的 SW 脚本入口
compatibility_date = "2025-06-19"               # 填今天或近一年内的日期
workers_dev        = true                        # 是否启用 workers.dev 预览
format             = "service-worker"            # 你的脚本写法：service-worker 或 modules

[site]                                         
  bucket  = "./public"           # 要当静态资源上传的目录
  include = ["**/*"]             # （可选）白名单
  exclude = ["serviceWorker.js"] # （可选）把 SW 脚本排除在静态资源之外
