# wrangler.toml

name               = "tobnoone_chatgpt_next_web"       # 你的项目名
compatibility_date = "2024-06-19"           # cf-worker 兼容日期，必须填

# 如果你只需要上传静态资源（没有自定义 Worker 逻辑）：
[site]
bucket  = "./public"     # 你的静态资源输出目录
include = ["**"]          # 打包时要包含的文件 glob
exclude = []              # 排除的文件 glob

# 以下两行可选，如果你希望直接在 workers.dev 子域名下预览
#workers_dev = true
