# wrangler.toml

name               = "tobnoonechatgptnextweb" 
compatibility_date = "2025-06-19"            

# ---------- 告诉 Wrangler 我要做一个静态站点 ----------
[site]
bucket      = "./public"     # 你的静态资源目录

# ---------- 构建 & 上传 配置（V2 推荐写法） ----------
[build]
# publish 前会自动执行这条命令，生成 workers-site/index.js
command = "wrangler site build ./public"

# upload 配置里指明了 entry-point 和 打包格式
[build.upload]
format = "service-worker"              # 或 "modules"，看你用的是哪种脚本格式
main   = "workers-site/index.js"       # site build 产出的文件
dir    = "./publish"                   # 要上传的静态资源目录

